site_name: Space-Time Matrix Tools Documentation
repo_url: https://github.com/tudelftgeodesy/stmtools/
repo_name: STM Tools

nav:
  - Getting Started:
    - About STM Tools: index.md
    - Installation: setup.md
  - Usage:
    - Initiate an STM: stm_init.md
    - Operations on STM: operations.md
    - Ordering an STM: order.md
  - Example Notebooks:
    - Example Operations: notebooks/demo_operations_stm.ipynb
    - Example Ordering: notebooks/demo_order_stm.ipynb
  - Contributing Guide:
    - Contributing Guidelines: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
  - Change Log: CHANGELOG.md
  - API Reference: api_reference.md


theme:
  name: material
  custom_dir: docs/notebooks/download_button
  logo: img/stmtools_logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: grey
      accent: pink
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

plugins:
- mkdocs-jupyter:
      include_source: True
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          docstring_section_style: list
          show_submodules: true
          show_root_heading: true
          show_source: true
          heading_level: 3
          relative_crossrefs: true
          parameter_headings: false
          separate_signature: true
          show_bases: true
          show_signature_annotations: true
          show_symbol_type_heading: true
          signature_crossrefs: true
          summary: true
          backlinks: tree
          scoped_crossrefs: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.highlight

extra:
  generator: false